DROP DATABASE IF EXISTS CATASTROFE;
CREATE DATABASE IF NOT EXISTS CATASTROFE;
USE CATASTROFE;


CREATE TABLE IF NOT EXISTS PAIS (
    ID_PAIS INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS CATASTROFE (
    ID_CATASTROFE INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    DATA_CATASTROFE DATE
);

CREATE TABLE IF NOT EXISTS VITIMA (
    ID_VITIMA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    EMAIL VARCHAR(25),
    SEXO CHAR(1),
    DATA_NASCIMENTO DATE,
    COD_CIDADE INT,
    FOREIGN KEY (COD_CIDADE)
        REFERENCES CIDADE (ID_CIDADE)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS ESTADO_PROVINCIA (
    ID_ESTADO_PROVINCIA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    COD_PAIS INT,
    FOREIGN KEY (COD_PAIS)
        REFERENCES PAIS (ID_PAIS)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CIDADE (
	ID_CIDADE INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    COD_ESTADO_PROVINCIA INT(40),
    FOREIGN KEY (COD_ESTADO_PROVINCIA)
        REFERENCES ESTADO_PROVINCIA (ID_ESTADO_PROVINCIA)
        ON UPDATE CASCADE ON DELETE CASCADE
    
);

CREATE TABLE IF NOT EXISTS DOADOR (
    ID_DOADOR INT NOT NULL,
    NOME DATE,
    EMAIL DATE,
    SEXO VARCHAR(10),
    COD_CIDADE INT,
    FOREIGN KEY (COD_CIDADE)
        REFERENCES CIDADE (ID_CIDADE)
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS DOACAO (
    ID_DOACAO INT NOT NULL PRIMARY KEY,
    COD_CATASTROFE INT,
    COD_DOADOR INT,
    VALOR FLOAT(22,3),
    FOREIGN KEY (COD_CATASTROFE)
        REFERENCES CATASTROFE (ID_CATASTROFE)
        ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (COD_DOADOR)
        REFERENCES DOADOR (ID_DOADOR)
        ON UPDATE CASCADE ON DELETE CASCADE
);
